// <auto-generated />
using System;
using Exchange.CryptoTransactions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exchange.CryptoTransactions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CryptoTransactionsDbContext))]
    [Migration("20260624134615_MakeBrokeredBuySagaCurrentStateNullable")]
    partial class MakeBrokeredBuySagaCurrentStateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exchange.BrokeredBuys.Messaging.BrokeredFiatCryptoBuySagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<decimal>("CapturedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("captured_amount");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_state");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_account_id");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<decimal?>("MaxTotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("max_total_cost");

                    b.Property<decimal?>("MaxUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("max_unit_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quote_currency");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("ReservedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("reserved_amount");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CustomerAccountId", "ClientOrderId")
                        .HasDatabaseName("ix_brokered_fiat_crypto_buy_saga_states_customer_order");

                    b.ToTable("brokered_fiat_crypto_buy_saga_states", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.BackgroundWorkerHeartbeatEntity", b =>
                {
                    b.Property<string>("WorkerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_name");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.HasKey("WorkerName");

                    b.ToTable("background_worker_heartbeats", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.BrokeredCryptoBuyExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_order_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_account_id");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExternalHedgeOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_hedge_order_id");

                    b.Property<decimal>("ExternalHedgeQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("external_hedge_quantity");

                    b.Property<decimal>("InternalFillQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("internal_fill_quantity");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quote_currency");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId", "AssetSymbol", "ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_brokered_crypto_buy_executions_customer_asset_order");

                    b.ToTable("brokered_crypto_buy_executions", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.BrokeredCryptoBuyQuoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_account_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<decimal>("ExternalHedgeQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("external_hedge_quantity");

                    b.Property<decimal>("InternalFillQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("internal_fill_quantity");

                    b.Property<DateTimeOffset>("MarketPriceObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("market_price_observed_at_utc");

                    b.Property<string>("PriceSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("price_source");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quote_currency");

                    b.Property<DateTimeOffset>("QuotedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quoted_at_utc");

                    b.Property<bool>("RequiresExternalHedge")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_external_hedge");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_brokered_crypto_buy_quotes_expires_at");

                    b.ToTable("brokered_crypto_buy_quotes", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoGatewayResilienceSettingsProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BreakDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("break_duration_seconds");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<double>("FailureRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("failure_ratio");

                    b.Property<int>("MaxParallelization")
                        .HasColumnType("integer")
                        .HasColumnName("max_parallelization");

                    b.Property<int>("MaxQueueingActions")
                        .HasColumnType("integer")
                        .HasColumnName("max_queueing_actions");

                    b.Property<int>("MinimumThroughput")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_throughput");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("OperationTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("operation_timeout_seconds");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("RetryDelayMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_delay_milliseconds");

                    b.Property<int>("SamplingDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("sampling_duration_seconds");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_crypto_gateway_resilience_settings_profiles_name");

                    b.ToTable("crypto_gateway_resilience_settings_profiles", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoGatewaySettingsProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("text")
                        .HasColumnName("api_secret");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("HttpTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("http_timeout_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSettingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_settings_json");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Name")
                        .HasDatabaseName("ix_crypto_gateway_settings_profiles_provider_name");

                    b.ToTable("crypto_gateway_settings_profiles", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoLedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_kind");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_crypto_ledger_entries_transaction_sequence");

                    b.ToTable("crypto_ledger_entries", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoLedgerTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operation_id");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_type");

                    b.HasKey("Id");

                    b.HasIndex("OperationType", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_crypto_ledger_transactions_operation");

                    b.ToTable("crypto_ledger_transactions", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoOwnershipPositionEntity", b =>
                {
                    b.Property<string>("CustomerAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_account_id");

                    b.Property<string>("AssetSymbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CustomerAccountId", "AssetSymbol");

                    b.ToTable("crypto_ownership_positions", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoSettingsProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BitcoinReferencePriceNok")
                        .HasColumnType("numeric")
                        .HasColumnName("bitcoin_reference_price_nok");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("EtherReferencePriceNok")
                        .HasColumnType("numeric")
                        .HasColumnName("ether_reference_price_nok");

                    b.Property<decimal>("ExternalHedgeSpreadBasisPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("external_hedge_spread_basis_points");

                    b.Property<decimal>("InitialBitcoinInventory")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_bitcoin_inventory");

                    b.Property<decimal>("InitialEtherInventory")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_ether_inventory");

                    b.Property<decimal>("InternalOnlySpreadBasisPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("internal_only_spread_basis_points");

                    b.Property<decimal>("MaxAllowedSlippageBasisPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("max_allowed_slippage_basis_points");

                    b.Property<int>("MaxBufferedHedgeCustomerBuys")
                        .HasColumnType("integer")
                        .HasColumnName("max_buffered_hedge_customer_buys");

                    b.Property<int>("MaxBufferedHedgeDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("max_buffered_hedge_delay_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("QuoteTtlSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("quote_ttl_seconds");

                    b.Property<decimal>("SimulationDefaultBitcoinAvailableBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_default_bitcoin_available_balance");

                    b.Property<decimal>("SimulationDefaultEtherAvailableBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_default_ether_available_balance");

                    b.Property<int>("SimulationMaxLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("simulation_max_latency_ms");

                    b.Property<int>("SimulationMinLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("simulation_min_latency_ms");

                    b.Property<decimal>("SimulationRejectRate")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_reject_rate");

                    b.Property<decimal>("SimulationTimeoutRate")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_timeout_rate");

                    b.Property<int>("TimeoutReconciliationScanIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_reconciliation_scan_interval_seconds");

                    b.Property<int>("TimeoutReconciliationStaleAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_reconciliation_stale_after_seconds");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_crypto_settings_profiles_name");

                    b.ToTable("crypto_settings_profiles", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoTransferIdempotencyReceiptEntity", b =>
                {
                    b.Property<string>("SourceAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_account_id");

                    b.Property<string>("AssetSymbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<decimal>("NetworkFee")
                        .HasColumnType("numeric")
                        .HasColumnName("network_fee");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_json");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.HasKey("SourceAccountId", "AssetSymbol", "IdempotencyKey");

                    b.ToTable("crypto_transfer_idempotency_receipts", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.ExternalHedgeBatchEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_account_id");

                    b.Property<DateTimeOffset?>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExecutedExternalOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("executed_external_order_id");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner_id");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quote_currency");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LeaseToken")
                        .HasDatabaseName("ix_external_hedge_batch_entries_lease_token");

                    b.HasIndex("CustomerAccountId", "ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_hedge_batch_entries_customer_order");

                    b.HasIndex("ExecutedAtUtc", "LeaseExpiresAtUtc", "AssetSymbol", "QuoteCurrency", "RequestedAtUtc")
                        .HasDatabaseName("ix_external_hedge_batch_entries_due_lookup");

                    b.ToTable("external_hedge_batch_entries", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.ExternalHedgeExecutionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<decimal>("ExecutedQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("executed_quantity");

                    b.Property<decimal>("ExecutedUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("executed_unit_price");

                    b.Property<string>("ExternalOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_order_id");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quote_currency");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at_utc");

                    b.Property<Guid?>("SettlementLedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_ledger_transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_hedge_execution_records_external_order");

                    b.HasIndex("SettledAtUtc", "ExecutedAtUtc")
                        .HasDatabaseName("ix_external_hedge_execution_records_settlement_state");

                    b.ToTable("external_hedge_execution_records", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.PlatformInventoryPositionEntity", b =>
                {
                    b.Property<string>("AssetSymbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("available_quantity");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AssetSymbol");

                    b.ToTable("platform_inventory_positions", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.SettingsChangeOutboxArchiveEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("publish_attempt_count");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc", "ArchivedAtUtc")
                        .HasDatabaseName("ix_settings_change_outbox_archive_entries_published_archived");

                    b.ToTable("settings_change_outbox_archive_entries", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.SettingsChangeOutboxEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner_id");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("publish_attempt_count");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_settings_change_outbox_entries_publish_state");

                    b.HasIndex("PublishedAtUtc", "LeaseExpiresAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_settings_change_outbox_entries_lease_state");

                    b.ToTable("settings_change_outbox_entries", (string)null);
                });

            modelBuilder.Entity("Exchange.Infrastructure.Scheduling.Persistence.CronJobExecutionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_name");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("text")
                        .HasColumnName("result_message");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("runner_id");

                    b.Property<DateTimeOffset>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAtUtc")
                        .HasDatabaseName("ix_cron_job_execution_records_job_started");

                    b.ToTable("cron_job_execution_records", (string)null);
                });

            modelBuilder.Entity("Exchange.Infrastructure.Scheduling.Persistence.CronJobStateEntity", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_name");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int?>("LastRunStatus")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_status");

                    b.Property<DateTimeOffset?>("LastStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_started_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner_id");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.HasKey("JobName");

                    b.HasIndex("NextRunAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_cron_job_states_due_lease");

                    b.ToTable("cron_job_states", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoLedgerEntryEntity", b =>
                {
                    b.HasOne("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoLedgerTransactionEntity", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
