// <auto-generated />
using System;
using Exchange.FiatTransactions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exchange.FiatTransactions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FiatTransactionsDbContext))]
    [Migration("20260624120011_InitialFiatTransactionsSchema")]
    partial class InitialFiatTransactionsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exchange.FiatTransactions.Infrastructure.Persistence.BrokeredCryptoBuySettlementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_order_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_account_id");

                    b.Property<decimal>("CustomerDebitAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("customer_debit_amount");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("FiatCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fiat_currency");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId", "ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_brokered_crypto_buy_settlements_customer_order");

                    b.ToTable("brokered_crypto_buy_settlements", (string)null);
                });

            modelBuilder.Entity("Exchange.FiatTransactions.Infrastructure.Persistence.FiatBalancePositionEntity", b =>
                {
                    b.Property<string>("FiatCurrency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fiat_currency");

                    b.Property<string>("AccountKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_kind");

                    b.Property<string>("AccountId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("AvailableAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("available_amount");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("FiatCurrency", "AccountKind", "AccountId");

                    b.ToTable("fiat_balance_positions", (string)null);
                });

            modelBuilder.Entity("Exchange.FiatTransactions.Infrastructure.Persistence.FiatLedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_kind");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("FiatCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fiat_currency");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_fiat_ledger_entries_transaction_sequence");

                    b.ToTable("fiat_ledger_entries", (string)null);
                });

            modelBuilder.Entity("Exchange.FiatTransactions.Infrastructure.Persistence.FiatLedgerTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operation_id");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_type");

                    b.HasKey("Id");

                    b.HasIndex("OperationType", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_fiat_ledger_transactions_operation");

                    b.ToTable("fiat_ledger_transactions", (string)null);
                });

            modelBuilder.Entity("Exchange.FiatTransactions.Infrastructure.Persistence.FiatLedgerEntryEntity", b =>
                {
                    b.HasOne("Exchange.FiatTransactions.Infrastructure.Persistence.FiatLedgerTransactionEntity", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
