// <auto-generated />
using System;
using Exchange.CryptoTransactions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exchange.CryptoTransactions.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoTransactionsDbContext))]
    [Migration("20260624065954_InitialPostgresBaseline")]
    partial class InitialPostgresBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoGatewaySettingsProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("text")
                        .HasColumnName("api_secret");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("HttpTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("http_timeout_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSettingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_settings_json");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Name")
                        .HasDatabaseName("ix_crypto_gateway_settings_profiles_provider_name");

                    b.ToTable("crypto_gateway_settings_profiles", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoSettingsProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BitcoinReferencePriceNok")
                        .HasColumnType("numeric")
                        .HasColumnName("bitcoin_reference_price_nok");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("EtherReferencePriceNok")
                        .HasColumnType("numeric")
                        .HasColumnName("ether_reference_price_nok");

                    b.Property<decimal>("ExternalHedgeSpreadBasisPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("external_hedge_spread_basis_points");

                    b.Property<decimal>("InitialBitcoinInventory")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_bitcoin_inventory");

                    b.Property<decimal>("InitialEtherInventory")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_ether_inventory");

                    b.Property<decimal>("InternalOnlySpreadBasisPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("internal_only_spread_basis_points");

                    b.Property<decimal>("MaxAllowedSlippageBasisPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("max_allowed_slippage_basis_points");

                    b.Property<int>("MaxBufferedHedgeCustomerBuys")
                        .HasColumnType("integer")
                        .HasColumnName("max_buffered_hedge_customer_buys");

                    b.Property<int>("MaxBufferedHedgeDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("max_buffered_hedge_delay_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("QuoteTtlSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("quote_ttl_seconds");

                    b.Property<decimal>("SimulationDefaultBitcoinAvailableBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_default_bitcoin_available_balance");

                    b.Property<decimal>("SimulationDefaultEtherAvailableBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_default_ether_available_balance");

                    b.Property<int>("SimulationMaxLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("simulation_max_latency_ms");

                    b.Property<int>("SimulationMinLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("simulation_min_latency_ms");

                    b.Property<decimal>("SimulationRejectRate")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_reject_rate");

                    b.Property<decimal>("SimulationTimeoutRate")
                        .HasColumnType("numeric")
                        .HasColumnName("simulation_timeout_rate");

                    b.Property<int>("TimeoutReconciliationScanIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_reconciliation_scan_interval_seconds");

                    b.Property<int>("TimeoutReconciliationStaleAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_reconciliation_stale_after_seconds");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_crypto_settings_profiles_name");

                    b.ToTable("crypto_settings_profiles", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.CryptoTransferIdempotencyReceiptEntity", b =>
                {
                    b.Property<string>("SourceAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_account_id");

                    b.Property<string>("AssetSymbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset_symbol");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_json");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.HasKey("SourceAccountId", "AssetSymbol", "IdempotencyKey");

                    b.ToTable("crypto_transfer_idempotency_receipts", (string)null);
                });

            modelBuilder.Entity("Exchange.CryptoTransactions.Infrastructure.Persistence.SettingsChangeOutboxEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("publish_attempt_count");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_settings_change_outbox_entries_publish_state");

                    b.ToTable("settings_change_outbox_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
